---
# Summary

- name: Write summary to install directory
  template:
    src: "{{ _item  }}"
    dest: "{{ hdf5_install_dir }}/{{ _item  | regex_replace('summary.j2', 'ansible_summary.txt' ) }}"
  loop_control:
    loop_var: _item
  with_items:
    - "summary.j2"
  register: hdf5_summary

- name: Display summary
  block:

  - name: Get summary
    command: "cat {{ hdf5_summary.results[0].dest }}"
    register: command_output

  - name: Print to console
    debug:
      msg: "{{ command_output.stdout }}"

  when: hdf5_verbose|bool